const express = require("express");
const router = express.Router();
const usersController = require("../logic/users.controller");
const isLogin = require("../../../middleware/isLogin.middleware");
const isAdmin = require("../../../middleware/isAdmin.middleware");
const getmeController = require("../logic/getme.controller");
const registerController = require("../logic/register.controller");
const loginMiddleware = require("../../../middleware/login.middleware");
const loginController = require("../logic/login.controller");
const isSuper = require("../../../middleware/isSuper.middleware");
const registerMiddleware = require("../../../middleware/register.middleware");
const registerforController = require("../logic/registercostumer.controller");
const editMiddleware = require("../../../middleware/edit.middleware");
const editMe = require("../logic/editme.controller");
const deleteController = require("../logic/delete.controller");
router.get("/", isAdmin, usersController);
router.get("/me", isLogin, getmeController);
router.post("/login", loginMiddleware, loginController);
router.post("/", isSuper, registerMiddleware, registerController);
router.post("/register", registerMiddleware, registerforController);
router.patch("/me", isLogin, editMiddleware, editMe);
router.delete("/:id", isAdmin, deleteController);
module.exports = router;
